Furniture/languages/Models/ApplicationUser.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace languages.Models
{
    public class ApplicationUser:IdentityUser
    {
        
    }
}

Furniture/languages/Models/Entities.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace languages.Models
{
	public class Entities:IdentityDbContext<ApplicationUser>
	{
		public Entities() : base()
		{

		}
		public Entities(DbContextOptions options) : base(options)
		{

		}

		public DbSet<furniture> furnitures { get; set; }


		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer("Server=db5079.public.databaseasp.net; Database=db5079; User Id=db5079; Password=C-i4m5?J3Dh#; Encrypt=False; MultipleActiveResultSets=True;");
			base.OnConfiguring(optionsBuilder);
		}
	}
}

Furniture/languages/Models/ErrorViewModel.cs
namespace languages.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Furniture/languages/Models/furniture.cs
using System.ComponentModel.DataAnnotations;

namespace languages.Models
{
	public class furniture
	{
		[Required]
		public int Id { get; set; }
		[Required]
		[MaxLength(100)]
	
		public string Name { get; set; }
		[Required]
		[RegularExpression (".*\\.(jpg$|png$)",ErrorMessage ="must end with .jpg or .png")]
		public string image { get; set; }
		[Required]

		public string Description { get; set; }

	}
}

Furniture/languages/Controllers/AccountController.cs
using languages.Models;
using languages.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace languages.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager ;

        public AccountController(SignInManager<ApplicationUser> signInManager,UserManager<ApplicationUser> userManager)
        {

            this.signInManager = signInManager;
            this.userManager = userManager;

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task< IActionResult> Register(registervm logIn)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser applicationUser = new ApplicationUser();
                applicationUser.Email = logIn.Email;
                applicationUser.UserName = logIn.Name;
                applicationUser.PasswordHash = logIn.Password;
                IdentityResult result = await userManager.CreateAsync(applicationUser,logIn.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(applicationUser, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var erroritem in result.Errors)
                    {
                        ModelState.AddModelError("Password", erroritem.Description);
                    }
                }

            }
            return View(logIn);
        }
        [HttpGet]
        public IActionResult login()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> login(LogIn loginVm)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser applicationUser = await userManager.FindByNameAsync(loginVm.Name);
                if (applicationUser != null)
                {
                    bool found = await userManager.CheckPasswordAsync(applicationUser, loginVm.Password);
                    if (found == true)
                    {
                        await signInManager.SignInAsync(applicationUser, loginVm.RememberMe);
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Name Or Password Wrong");
            }
            return View(loginVm);
        }
        public async Task<IActionResult> logout(LogIn vm)
        {

            await signInManager.SignOutAsync();
            return RedirectToAction("login");
        }


    }
}

Furniture/languages/Controllers/HomeController.cs
using System.Diagnostics;
using languages.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace languages.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		Entities entities;


		public HomeController(ILogger<HomeController> logger,Entities entities)
		{
			_logger = logger;
			this.entities = entities;
		}
		public ActionResult Details(int Id) {

			var mov=entities.furnitures.FirstOrDefault(x => x.Id == Id);
			return View(mov);
		}
		
		public IActionResult Index()
		{
			var funs=entities.furnitures.ToList();
			return View(funs);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Furniture/languages/Controllers/furnitureController.cs
using languages.Models;
using Microsoft.AspNetCore.Mvc;


namespace languages.Controllers
{
	public class furnitureController : Controller
	{
		Entities Entities;
        public furnitureController(Entities entities)
        {
			Entities = entities;
            
        }
		[HttpGet]
		public IActionResult New()
		{
			return View();
		}
		[HttpPost]
		public IActionResult New(furniture furniture)
		{
			Entities.furnitures.Add(furniture);
			Entities.SaveChanges();
			return RedirectToAction("Index", "Home");
			
		}
		[HttpGet]
		public IActionResult Edit(int id) {
			var fun=Entities.furnitures.FirstOrDefault(i=> i.Id==id);
			return View(fun);
		}
		public IActionResult Edit(furniture newfun,int id) {
            if (newfun.Name !=null)
            {
                var oldfun = Entities.furnitures.FirstOrDefault(x => x.Id == id);
                oldfun.Name = newfun.Name;
                oldfun.Description = newfun.Description;
                oldfun.image = newfun.image;
                Entities.SaveChanges();
				return RedirectToAction("Index", "Home");
            }
            
			return View(newfun);
		}
        public IActionResult Delete(int id)
        {
            var product = Entities.furnitures.FirstOrDefault(x => x.Id == id);
            if (product == null) return NotFound();
            return View(product);
        }
        public IActionResult ConfirmDelete(int id)
		{
			var fun=Entities.furnitures.FirstOrDefault(x=> x.Id==id);
			Entities.furnitures.Remove(fun);
			Entities.SaveChanges();
			return RedirectToAction("Index", "Home");
		}
		

	}
}

Furniture/languages/Views/Home/Details.cshtml
@model furniture

@{
    ViewBag.Title = "Movie Details";
}
<style>
    .text{
        font-size:20px;
        font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="image-container">
                <img src="~/img/@Model.image" alt="Movie Image" class="img-fluid rounded">
            </div>
        </div>
        <div class="col-md-8">
            <div class="details-container">
                <h2 class="text">@Model.Name</h2>
                <p class="text">@Model.Description</p>
            </div>
        </div>
        <br />
        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-md-8">
                <div class="details-container">
                    <a style="margin:10px;background-color:darkgray" class="btn btn-secondary" href="@Url.Action("Edit","furniture", new { id = Model.Id })">Edit</a>
                    <a class="btn btn-secondary"style="background-color:darkgray" href="@Url.Action("Delete","furniture", new { id = Model.Id })">Delete</a>
                </div>
            </div>
        }
      
    </div>
</div>

Furniture/languages/Views/Home/Index.cshtml
@model List<furniture>

<div id="main">
    <div id="content">
        <div class="box">
            <br />
            <div class="container-fluid p-0 pb-5 justify-content-center">
                <div class="owl-carousel header-carousel position-relative mb-5">
                    <div class="owl-carousel-item position-relative" >
                        
                        <img class="img-fluid" src="~/img//why-choose-us-img.jpg" style="width:1500px;height:550px;">
                        <h3 class="justify-content-center align-item-center" style="font-family:'Times New Roman', Times, serif;margin-left:130px;padding-left:80px;margin-bottom:50px;margin-top:20px;">
                            Here You Can Find What You Want And Either When You Need To Add Yours 
                        </h3>
                    </div>
                </div>
            </div>
           
            <div class="furniture-container">
                @foreach (var item in Model)
                {
                    <div class="furniture-item">
                        <a href="@Url.Action("Details", new { id = item.Id })">
                            <div class="furniture-image">
                                <img src="/img/@item.image" alt="@item.Name" />
                                <span class="name" style="font-family:'Times New Roman', Times, serif;">@item.Name</span>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .furniture-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px; /* Adjust the gap between items as needed */
        justify-content: start; /* Align items to the start of the container */
        padding-left: 70px; /* Adjust to match your design */
    }

    .furniture-item {
        flex: 1 1 calc(50% - 20px); /* 50% width minus gap size, adjust for 2 columns */
        box-sizing: border-box;
    }

    .furniture-image {
        display: block;
        width: 100%;
        max-width: 100%;
    }

        .furniture-image img {
            width: 100%;
            height: auto;
            display: block;
        }

    .name {
        display: block;
        text-align: center;
        margin-top: 10px;
        font-size:large;
    }
    h3:hover{
        color:mediumpurple;
        transform: scale(1.0);
        margin-top: -5px; /* Adjust the top margin to make room for expansion */
        margin-bottom: -5px; /* Adjust the bottom margin to make room for expansion */
        padding: 0.5rem 1rem;
    }
</style>

Furniture/languages/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Furniture</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/languages.styles.css" asp-append-version="true" />
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <link rel="stylesheet" href="~/css/style.css" type="text/css" media="all" />
                <script type="text/javascript" src="~/js/jquery-1.4.2.min.js"></script>
                <script type="text/javascript" src="~/js/jquery-func.js"></script>
</head>
<body >
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm] border-bottom box-shadow mb-3" style="background-color:black">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:aqua">Furniture</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="navbar-nav ">
                                <a class="nav-link text-light" asp-controller="Account" asp-action="login">Login</a>
                            </li>
                            
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="furniture" asp-action="new">Add furniture</a>
                            </li>


                            <li class="navbar-nav ">
                                <a class="nav-link text-light " asp-controller="Account" asp-action="logout">Logout</a>
                            </li>
                        }


                      

                    </ul>
                </div>
            </div>
        </nav>
    </header>
           
                <div id="shell">
                    <div id="header">
                       

                        <div class="container" >
                            <main role="main" class="pb-3">
                                @RenderBody()
                            </main>
                        </div>
                    </div>
                </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Furniture/languages/Views/furniture/Delete.cshtml
<div class="container">
    <h2>Product Details</h2>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">ID: @Model.Id</h4>
            <h4 class="card-title">Name: @Model.Name</h4>
           
            <h4 class="card-title">Image: @Model.image</h4>
            
        </div>
    </div>

    <form asp-action="ConfirmDelete" asp-route-id="@Model.Id" method="post" class="mt-3">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="Index" asp-controller="Home" class="btn btn-secondary" style="background-color:darkgray">Cancel</a>
    </form>
</div>

Furniture/languages/Views/furniture/Edit.cshtml
@model languages.Models.furniture

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Furniture</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <br />
                <br />
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <br />

                <label asp-for="image" class="control-label"></label>
                <input asp-for="image" type="file" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <br />

                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
                <br />
            <br />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />

<div>
    <a asp-action="Index" asp-controller="home">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Furniture/languages/Views/furniture/New.cshtml
@model languages.Models.furniture

@{
    ViewData["Title"] = "New";
}

<h1>New Furniture</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="New" asp-controller="furniture">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input asp-for="image" type="file" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <br />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>